# Adapt and copy this file to cfg/config.toml for productive configuration
[delegate]
address = "ASJBHz4JfWVUGDyN61hMMnW1Y4ZCTBHL1K"
pubkey = "027acdf24b004a7b1e6be2adf746e3233ce034dbb7e83d4a900f367efc4abd0f21"

[voters]
shareRatio = 0.70 #percent goes to voters
txdescription = "delegate: voters share. Thank you! |tx by ark-go"
fidelity = true
fidelityLimit = 24  #fidelity limit in hours
minamount = 0.0 #minimum amount limit for payout.
deductTxFees = true #if true tx fees are deducted from recepients
blocklist = "" #comma separated address list of addresses of voters to block
whitelist = "" #comma separated address list of addresses of voters to allow
capBalance = false
balanceCapAmount = 0.0
blockBalanceCap = true #Should the payout be completely blocked, false = pay profit for cap

[costs]
address = "ANqeL7CP2som7q9NFbRuaUc5WUnwYkSbFY" #costs
shareRatio = 0.15

[reserve]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.15

[personal]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.0

#ARK-POOL SERVER SETTINGS
[server]
port = 54000
address = "0.0.0.0"
dbfilename = "payment.db"
autoconfigPeer = "" #node ip address and port to start talking with blockchain and configure from it there (autoconfigure)
#If you are running on the same server do NOT set 127.0.0.1:4001 but your real ip. The node blocks 127 ip's.
network = "MAINNET" #if autoconfigpeer is not set, network is used

#FRONTEND settings related to page generation
[web]
frontend = false
twitter = "ChrisDelegate"  #twitter user name for twitter feed on main page if empty not shown
reddit = "" #reddit link to delegate description - if empty not shown
slack = "" #slack link to delegate - if empty not shown
email = "" #email link to delegate - if empty not shown
arkforum = "" #http link to forum proposal - if empty not shown
arknewsaddress = "" #arknews address to follow and display news from JARUNIK 
gacode = "ua-cxdssaa" #google analytics code

