# Adapt and copy this file to settings/config.toml for productive configuration
# Do NOT change the headers in brackets, example: [delegate]
[delegate]
address = "ASJBHz4JfWVUGDyN61hMMnW1Y4ZCTBHL1K"
pubkey = "027acdf24b004a7b1e6be2adf746e3233ce034dbb7e83d4a900f367efc4abd0f21"

[voters]
shareRatio = 0.70 #percent goes to voters
txdescription = "delegate: voters share. Thank you! |tx by ark-go"
fidelity = true # reduce share of new voters
fidelityLimit = 24  #fidelity limit in hours - calculation: profit * (voted time / fidelityLimit)
minamount = 0.0 #minimum amount limit for payout.
minVoteTime = 0 #minimum vote time in hours to receive payout
deductTxFees = true #if true tx fees are deducted from recepients, if false fees are paid by reserver share
blocklist = "" #comma separated address list of addresses of voters to block
whitelist = "" #comma separated address list of addresses of voters to allow ( only applies to cap options)
capBalance = false #should the payout be capped?
balanceCapAmount = 0.0 #treshold to cap the balance
blockBalanceCap = true #Should the payout be completely blocked, false = pay profit for cap

[costs]
address = "ANqeL7CP2som7q9NFbRuaUc5WUnwYkSbFY" #costs
shareRatio = 0.15
txdescription = "delegate costs. |tx by ark-go" #not longer than 64 chars

[reserve]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.15
txdescription = "delegate reserve. |tx by ark-go" #not longer than 64 chars

[personal]
address = "AKB7z6QLpCctVsj62nA7pBHk9zF6ocxZdJ" #reserve
shareRatio = 0.0
txdescription = "delegate personal. |tx by ark-go" #not longer than 64 chars

[client]
network = "MAINNET" #which network is active when application starts
dbfilename = "payment.db"
payloadsize = 30 #number of transaction sent to block in one payload
multibroadcast = 10 #to how many peers at once - we can multibroadcast
autoconfigPeer = "" #node ip address and port to start talking with blockchain and configure from it there (autoconfigure). 
#If you are running on the same server do NOT set 127.0.0.1:4001 but your real ip. The node blocks 127 ip's.
